In [ ]:
!pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.7/dist-packages (0.14.0)
Requirement already satisfied: matplotlib>=1.5.1 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (3.2.2)
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.19.5)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from mlxtend) (57.4.0)
Requirement already satisfied: pandas>=0.17.1 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.1.5)
Requirement already satisfied: scipy>=0.17 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.4.1)
Requirement already satisfied: scikit-learn>=0.18 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.0.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (1.3.2)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (2.8.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (3.0.6)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (0.11.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.17.1->mlxtend) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=1.5.1->mlxtend) (1.15.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.18->mlxtend) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.18->mlxtend) (3.0.0)

In [ ]:
import pandas as pd
df = pd.read_excel('drive/MyDrive/Colab Notebooks/CRM - Product Recommendation/Customer Preference Survey.xlsx')

In [ ]:
df.head(5)

                Timestamp  Transaction  ...  ยาดม  ไฟส่องหน้าไลฟ์สด
0 2021-10-17 17:43:37.985            1  ...     0                 0
1 2021-10-17 17:43:40.565            2  ...     0                 0
2 2021-10-17 17:43:46.302            3  ...     1                 1
3 2021-10-17 17:43:48.912            4  ...     0                 0
4 2021-10-17 17:43:54.754            5  ...     1                 0

[5 rows x 43 columns]

In [ ]:
df = df.drop('Timestamp', 1)
df = df.drop('Transaction', 1)

In [ ]:
df.head(5)

   playstation5  เครื่องทำขนมปัง  ...  ยาดม  ไฟส่องหน้าไลฟ์สด
0             0                0  ...     0                 0
1             0                0  ...     0                 0
2             0                0  ...     1                 1
3             0                0  ...     0                 0
4             0                0  ...     1                 0

[5 rows x 41 columns]

In [40]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

frequent_itemsets = apriori(df, min_support = 0.35, use_colnames=True)

In [41]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.5)
rules.head(10)

                 antecedents                consequents  ...  leverage  conviction
0  (ยาดม, หม้อทอดไร้น้ํามัน)            (เครื่องซักผ้า)  ...  0.124038    2.457447
1            (เครื่องซักผ้า)  (ยาดม, หม้อทอดไร้น้ํามัน)  ...  0.124038    1.728723

[2 rows x 9 columns]

Interpret
- หา Itemset ที่มี support อย่างต่ำ 35% หมายความว่า item นั้นๆต้องปรากฏในตะกร้าอย่างต่ำ 25% จากจำนวนตะกร้าทั้งหมด เพื่อตัดสินค้าที่มีจำนวนน้อยออกไป และเพื่อลดจำนวน rules ลง
- rule ที่เราสนใจ คือ ให้มี lift อย่างต่ำ 1.5 หมายความว่า มีความน่าจะเป็นที่จะซื้อสินค้าที่เป็น associated item มากขึ้น 50%
- จากผลที่ออกมาอธิบายได้ว่า คนที่ซื้อยาดม และหม้อทอดไร้น้ำมัน จะซื้อเครื่องซักผ้าด้วย ซึ่งสามารถอธิบายได้ว่ากลุ่มลูกค้ากลุ่มนี้จะเป็นคนทำงานที่อยู่คอนโด เพราะไม่ค่อยมีเวลา ดังนั้นจึงต้องซื้อเครื่องซักผ้าและหม้อทอดไร้น้ำเมื่อสำหรับการใช้ชีวิต สำหรับยาดมก็ตอบโจทย์คนทำงานที่ต้องการสูดให้สมองโล่งเพื่อทำงานได้ดีขึ้น